### ISSUE TITLE
How fast

### ISSUE THREAD

**Issue by stryngs** [Caesurus/airventriloquist#1]
Came across your code via dragon on twitter.  Curious to know just how fast it is and if you plan on working on it further?  I do the same thing, but in Python and results are a crapshoot at best.  Would love to collaborate further.

**Comment by Caesurus** [comment]
I did my initial proof on concept in python but I was having problems beating the response from the AP. I don't remember the exact timing but it was inconsistent like you said. I couldn't beat LAN pings, and internet pings occasionally.

Once I rewrote it in C I was able to beat the response from the AP every time. Again I don't have exact timings (this was two years ago). I believe it can even beat the a ping response for the AP itself. 

It was a fun little project at the time since I wanted to do a blackhat talk submission, but haven't work on it since. I'm currently just playing CTFs. Let me know what you've got so far. I'm open to collaborating/helping out occasionally but can't spend too much time on it.

**Comment by stryngs** [comment]
Would there be a chance you could hop on IRC so we could actively chat?

**Comment by Caesurus** [comment]
Sure, what server/channel?

**Comment by stryngs** [comment]
irc.freenode.net in ##ha
my nick is... stryngs

**Comment by Caesurus** [comment]
BTW, i don't seem to have an email address for you. Let's see if this works.
I saw this and thought of your project:
http://cppyy.readthedocs.io/en/latest/

**Comment by stryngs** [comment]
info [at] ethicalreporting.org

Sorry for the delay, Defcon Prep + Defcon + getting back in the swing of things, takes a toll on the body =)
